name: CI/CD Pipeline - Static Site

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_IMAGE: fdc2
  DOCKERHUB_USERNAME: cwfowers
  NODE_VERSION: '22'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Debug npm and node versions
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"

    - name: Install dependencies
      run: |
        echo "Installing dependencies for static build..."
        npm ci --verbose
      env:
        NPM_CONFIG_LOGLEVEL: verbose

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm run test:run

    - name: Build static application
      run: npm run build

    - name: Verify build output
      run: |
        echo "Build output:"
        ls -la dist/
        echo "CSV data files:"
        ls -la public/data/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-files
        path: |
          dist/
          public/data/
        retention-days: 1

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tags: ${{ steps.meta.outputs.tags }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
        labels: |
          org.opencontainers.image.title=Fire Direction Calculator - Static Site
          org.opencontainers.image.description=Static React PWA for mortar fire direction calculations with offline CSV data
          org.opencontainers.image.vendor=FDC2
          org.opencontainers.image.licenses=MIT

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        build-args: |
          NODE_ENV=production

    - name: Update Docker Hub description
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      continue-on-error: true
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}
        readme-filepath: ./DOCKER_DEPLOYMENT.md

  deploy-notification:
    needs: [docker]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Deployment Success Notification
      run: |
        echo "🎯 Fire Direction Calculator deployed successfully!"
        echo "🐳 Docker image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest"
        echo "📊 Image digest: ${{ needs.docker.outputs.image-digest }}"
        echo "🏷️  Tags: ${{ needs.docker.outputs.image-tags }}"
